version: "3"
services:
  web:
    build: 
      context: .      
    command: ["npm", "run", "start"]    
    env_file: .env    
    ports:
        - "3000:3000"
    volumes:      
      - ./:/var/react-webpack-template
 